site_name: ISO TC 204 Information
site_description: Information about ISO TC 204 standardization efforts
repo_url: https://github.com/ISO-TC204/ISO-TC204.github.io
nav:
  - TC204 on ISO.org: https://www.iso.org/committee/54706.html
  - Home: index.md
  - About:
    - About TC 204: about.md
    - About ISO Documents: about-docs.md
    - Intro to ITS: intro.md
    - Business Plan: assets/pdf/business-plan-2026.pdf
    - Contact us: contact.md
    - Vocabulary: https://isotc204.org/iso14812/
    - Acknowledgements: acknowledgements.md
    - Contributions: contributor.md
    - FAQs: faq.md
  - Work: 
    - Overview: work.md
    - Foundational concepts: foundational.md
    - Architecture (WG 1): wg1/index.md
    - Big data and AI (WG 20): wg20/index.md
    - City data model - Transport (JWG 1): jwg1/index.md
    - Communications (WG 16): wg16/index.md
    - Cooperative systems (WG 18): wg18/index.md
    - Coordination (AG 4): ag4/index.md
    - Cybersecurity (AHG 2): ahg2/index.md
    - Driving automation and active safety systems (WG 14): wg14/index.md
    - Fee and toll collection (WG 5): wg5/index.md
    - Fleet management (WG 7): wg7/index.md
    - Geographic data (WG 3): wg3/index.md
    - Geographic information systems (JWG 11): tc211jwg11/index.md
    - Identifiers (AG 2): ag2/index.md
    - Mobility integration (WG 19): wg19/index.md
    - Nomadic devices in ITS (WG 17): wg17/index.md
    - Operational improvement (AG 3): ag3/index.md
    - Public transport/emergency (WG 8): wg8/index.md
    - Publication and marketing (AG 5): ag5/index.md
    - Registry for ITS Identifiers (AG 2): ag2/index.md
    - Transport mgmt and control (WG 9): wg9/index.md
    - Traveller information (WG 10): wg10/index.md
  - Registries: 
    - Overview: registries.md
    - RITSI: https://isotc204.org/iso5345
    - RITSO: 
      - Home: ritso/index.md
      - Ontology formats: ritso/ontology_formats.md
      - Naming conventions: ritso/naming_conventions.md
      - Turtle file format: ritso/turtle.md
      - Ontology registry: ritso/python/ontology_registry.md
      - Concept registry: ritso/python/concept_registry.md
      - Imported ontologies:
        - foaf: https://isotc204.org/ontology-import-foaf
        - geo: https://isotc204.org/ontology-import-geo
        - gr: https://isotc204.org/ontology-import-gr
        - i72: https://isotc204.org/ontology-i72-v1
        - org: https://isotc204.org/ontology-import-org
        - prov: https://isotc204.org/ontology-import-prov
        - schema: https://isotc204.org/ontology-import-schema
        - time: https://isotc204.org/ontology-import-time
        - wgs84: https://isotc204.org/ontology-import-wgs84
        - xsd: https://isotc204.org/ontology-import-xsd
      - City Data Model:
        - Part 1: https://isotc204.org/ontology-cdm-p1-v1
        - Part 2: https://isotc204.org/ontology-cdm-p2-v1
        - Part 3: https://isotc204.org/ontology-cdm-p3-v1
      - ITS:
        - Core: https://isotc204.org/ontology-its-core-v1
        - Agent: https://isotc204.org/ontology-its-agent-v1
        - Location: https://isotc204.org/ontology-its-location-v1
        - Regulation: https://isotc204.org/ontology-its-regulation-v1
        - Time: https://isotc204.org/ontology-its-time-v1
        - Transport Network: https://isotc204.org/ontology-its-transport-network-v1
        - Vehicle: https://isotc204.org/ontology-its-vehicle-v1
  - Standards: 
    - Overview: standards.md
    - Extracts:
      - ISO/TR 4448-1: extracts/ISO_4448-1/index.md
      - EN ISO 12855: extracts/EN_ISO_12855/index.md
      - ISO 14823-1: extracts/ISO_14823-1/index.md
      - EN ISO 14906: extracts/EN_ISO_14906/index.md
      - ISO 15622: extracts/ISO_15622/index.md
      - EN ISO 17573-1: extracts/EN_ISO_17573-1/index.md
      - ISO 17748-3: extracts/ISO_17748-3/index.md
      - ISO/TS 19091: extracts/ISO_TS_19091/index.md
      - ISO 21219-19: extracts/ISO_21219-19/index.md
      - ISO 21214: extracts/ISO_21214/index.md
      - ISO 23792-1: extracts/ISO_23792-1/index.md
      - ISO 26683-2: extracts/ISO_26683-2/index.md
      - ISO/TS 22726-1: extracts/ISO_TS_22726-1/index.md
      - ISO/TS 22741-10: extracts/ISO_TS_22741-10/index.md
    - METR: https://isotc204.org/iso24315/
    - Vocabulary: https://isotc204.org/iso14812/
  - Cybersecurity: 
    - Introduction: cybersecurity/index.md
    - Beginners Guide: cybersecurity/beginners-guide.md 
    - Cryptography Fundamentals: cybersecurity/primer-cryptography.md
    - ITS Security Regulations and Standards: 
      - Overview: cybersecurity/its-security-standards.md
      - Certificate Policy (CP): cybersecurity/policies-cp.md
      - SCMS Policy: cybersecurity/policies-scms.md
      - CCMS Policy: cybersecurity/policies-ccms.md
      - Device Hardening Guide: cybersecurity/device-hardening-guide.md
    - ITS Threat analysis: cybersecurity/its-threat-analysis.md
    - ITS Cybersecurity Patterns: 
      - Overview: cybersecurity/its-security-patterns.md
      - Secure ITS Management Patterns: cybersecurity/patterns-management.md
      - Application Security Patterns: cybersecurity/patterns-application.md
      - Edge Device Security Patterns: cybersecurity/patterns-edge.md
      - Network and Transport Security Patterns: cybersecurity/patterns-network.md
      - Deployment and Integration Security Patterns: cybersecurity/patterns-deployment.md
      - Developer Patterns: cybersecurity/patterns-developer.md
      - Secure ITS Management Patterns: cybersecurity/patterns-management.md
    - Interoperability strategies: cybersecurity/its-interoperability-strategies.md
    - Stakeholder guidance: 
      - Overview: cybersecurity/its-stakeholder-guidance.md
      - Standards developers: cybersecurity/stakeholder-standards-developer.md
      - Cybersecurity Oversight and Policy Authorities: cybersecurity/stakeholder-policy-maker.md
      - Infrastructure Owner Operators (IOOs): cybersecurity/stakeholder-ioo.md
      - ITS Application Developers: cybersecurity/stakeholder-appdev.md
      - Certificate Management Authorities: cybersecurity/stakeholder-certmgmt.md
      - Original Equipment Manufacturers (OEMs): cybersecurity/stakeholder-oem.md
    - Common Security Gaps: cybersecurity/its-security-gaps.md
    - Glossary: cybersecurity/cybersecurity-glossary.md
  - Resources: resources.md
site_url: https://isotc204.org/
extra:
  CNAME: isotc204.org
copyright: CC BY 4.0
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - content.tooltips
    - header.auto_hide
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
plugins:
  - macros:
      module_name: macros
  - search
  - redirects:
      redirect_maps:
        'metr.md': 'https://isotc204.org/iso24315/'
        'vocabulary.md': 'https://isotc204.org/iso14812/'
  - git-revision-date-localized:
      type: date
      exclude:
        - temp_dir/**
      fallback_to_build_date: true 
      strict: false  
  - include-markdown
  - multirepo:
      cleanup: true
      keep_docs_dir: false
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - resources/glossary.md
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
extra:
  search:
    highlight: true



    
    
